[package]
name = "ckb-sdk"
version = "0.15.0"
authors = ["Linfeng Qian <thewawar@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
serde_json = "1.0"
numext-fixed-hash = "~0.1"
bech32 = "0.6.0"
bytes = { version="0.4", features = ["serde"] }
bincode = "1.1.4"
log = "0.4.6"
# fs2 = "0.4.3"
jsonrpc-client-core = "0.5.0"
jsonrpc-client-http = "0.5.0"
rocksdb = { version = "0.12.2", default-features = false }
secp256k1 = {version = "0.12.2" }
faster-hex = "0.3"
fnv = "1.0.3"
aes-ctr = "0.3.0"
scrypt = "0.2.0"
rand = "0.6.5"
tiny-keccak = "1.4"
byteorder = "1.3.2"
bitcoin_hashes = "0.3.2"
uuid = { version = "0.7.4", features = ["v4"] }
chrono = "0.4.6"
failure = "0.1.5"

ckb-core = { git = "https://github.com/nervosnetwork/ckb", branch = "develop" }
ckb-script = { git = "https://github.com/nervosnetwork/ckb", branch = "develop" }
ckb-jsonrpc-types = { git = "https://github.com/nervosnetwork/ckb", branch = "develop" }
ckb-hash = { git = "https://github.com/nervosnetwork/ckb", branch = "develop" }
ckb-crypto = { git = "https://github.com/nervosnetwork/ckb", branch = "develop", features = ["secp", "bech32"] }
